apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: go
  labels:
    app: go
spec:
  selector: 
    matchLabels: 
      app: go
  template: 
    metadata: 
      name: go-pod 
      labels: 
        app: go 
      annotations: 
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'go-app-role'
        vault.hashicorp.com/agent-inject-secret-go-database-config.txt: 'internal/data/go-database-config/credentials/'
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "internal/data/go-database-config/credentials/" -}}
            {{- range $key, $value := .Data.data }}
              export {{ $key }}="{{ $value }}"
            {{- end}}
          {{- end }}
    spec: 
      serviceAccountName: go-app-sa
      containers: 
      - name: go-con 
        image: pranay1717/go-mysql-connect:latest 
        resources: 
          requests: 
            cpu: 200m 
            memory: 200Mi
        envFrom:
          - configMapRef:
              name: go-config
        env: 
          - name: VAULT_ADDR 
            value: https://127.0.0.1:8200 
          - name: VAULT_NAMESPACE 
            value: vault
        ports: 
        - containerPort: 8080
        args: ['sh', '-c', 'echo "Starting args" && source /vault/secrets/config && /docker-gs-ping']
---

apiVersion: v1 
kind: Service 
metadata:
  name: go-service 
  labels: 
    app: go
spec: 
  selector:
    app: go
  ports:
  - port: 8080
    targetPort: 8080